### ISSUE TITLE
Requires elixir to use the hex package

### ISSUE THREAD

**Issue by tsloughter** [rossjones/nifty#7]
The hex package was published with `mix` as the build tool. This results in an error when trying to use it from rebar3:

```
===> Compiling nifty
===> Error building application nifty:
     No project builder is configured for type mix
```

rebar3 respects that the build tool is listed as only `mix` in the hex metadata. It is such a rare case (this is the first time I've seen this issue) that I'd rather not have to add logic to check that if "mix" is the build tool but there is a `rebar.config` to continue and ignore the hex metadata.

Could you re-publish with rebar3?

**Comment by rossjones** [comment]
It has been (unfortunately) a while since I've been able to work with elixir etc, am I right in thinking that I need to just add `rebar3` (or `rebar`) to `build_tools` and a rebar.config?

**Comment by tsloughter** [comment]
Oh, woops, I got this all wrong :).

The published package is yours which *is* an Elixir project. I thought it was https://github.com/parapluu/nifty which is a rebar3 project and figured they simply published with mix years back and never updated.

Sorry about that, closing this issue.
